=== albarro/albarro.github.io/personajes.xsd
<?xml version="1.0" encoding="Windows-1252" ?>
<xs:schema xmlns="http://tempuri.org/personajes" elementFormDefault="qualified" targetNamespace="http://tempuri.org/personajes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="personajes">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="personaje" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="personaje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="raza" />
        <xs:element ref="descripcion" />
        <xs:element ref="transfondo" />
        <xs:element ref="alinemiento" />
        <xs:element ref="vida" />
        <xs:element ref="movimiento" />
        <xs:element ref="nivel" />
        <xs:element ref="clase" />
        <xs:element ref="experiencia" />
        <xs:element ref="atributos" />
        <xs:element ref="competencias" />
        <xs:element ref="inventario" />
        <xs:element ref="magias" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="raza" type="xs:string" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="transfondo" type="xs:string" />
  <xs:element name="alinemiento" type="xs:string" />
  <xs:element name="vida" type="xs:integer" />
  <xs:element name="movimiento" type="xs:integer" />
  <xs:element name="nivel" type="xs:integer" />
  <xs:element name="clase" type="xs:string" />
  <xs:element name="experiencia" type="xs:integer" />
  <xs:element name="atributos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fuerza" />
        <xs:element ref="destreza" />
        <xs:element ref="constitucion" />
        <xs:element ref="inteligencia" />
        <xs:element ref="sabiduria" />
        <xs:element ref="carisma" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fuerza">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="destreza">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="constitucion">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="inteligencia">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="sabiduria">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="carisma">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
        <xs:maxInclusive value="20" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="competencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bonificador" />
        <xs:element ref="salvaciones" />
        <xs:element ref="idiomas" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="bonificador" type="xs:integer" />
  <xs:element name="salvaciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="atributo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="atributo" type="xs:string" />
  <xs:element name="idiomas">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="idioma" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="idioma" type="xs:string" />
  <xs:element name="inventario">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="20" ref="objeto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="objeto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="descripcion" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="magias">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="atributo" />
        <xs:element ref="salvacion" />
        <xs:element ref="bonificador" />
        <xs:element minOccurs="0" maxOccurs="20" ref="nivelMagia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="salvacion" type="xs:integer" />
  <xs:element name="nivelMagia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="usos" />
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="magia" />
      </xs:sequence>
      <xs:attribute name="n" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="usos" type="xs:integer" />
  <xs:element name="magia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="descripcion" />
        <xs:element ref="componentes" />
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="componentes" type="xs:string" />
</xs:schema>

=== albarro/albarro.github.io/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="personajes.xsl" ?>
<personajes xsi:schemaLocation="http://tempuri.org/personajes personajes.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://tempuri.org/personajes">

    <personaje nombre="Prueba">

        <raza>Prueba</raza>
        <descripcion>Prueba no es mas que un personaje de prueba, un monton de texto sin mas objetivo que probar programas</descripcion>
        <transfondo>Fichero xml vacio</transfondo>
        <alinemiento>Neutral Neutral</alinemiento>

        <vida>500</vida>
        <movimiento>50</movimiento>

        <nivel>50</nivel>
        <clase>Tester</clase>
        <experiencia>55555</experiencia>

        <atributos>
            <fuerza>20</fuerza>
            <destreza>20</destreza>
            <constitucion>20</constitucion>
            <inteligencia>1</inteligencia>
            <sabiduria>1</sabiduria>
            <carisma>20</carisma>
        </atributos>

        <competencias>
            <bonificador>5</bonificador>
            <salvaciones>
                <atributo>Inteligencia</atributo>
                <atributo>Constitucion</atributo>
            </salvaciones>
            <idiomas>
                <idioma>Comun</idioma>
                <idioma>Binario</idioma>
            </idiomas>
        </competencias>

        <inventario>
            <objeto nombre="Null Pointer">
                <descripcion>
                    Arma capaz de destruir la mente de cualquier enemigo
                    Daño:2d100
                </descripcion>
            </objeto>
            <objeto nombre="Stack">
                <descripcion>
                    Poderosa armadura capaz de guardar los golpes
                    Armadura:20
                </descripcion>
            </objeto>
        </inventario>

        <magias>
            <atributo>Inteligencia</atributo>
            <salvacion>20</salvacion>
            <bonificador>5</bonificador>
            <nivelMagia n="0">
                <usos>50</usos>
                <magia nombre="Prueba">
                    <descripcion>Magia probatoria</descripcion>
                    <componentes>Debuger</componentes>
                </magia>
            </nivelMagia>
        </magias>

    </personaje>

    <personaje nombre="Antor">

        <raza>Enano de las Colinas</raza>
        <descripcion>Prueba no es mas que un personaje de prueba, un monton de texto sin mas objetivo que probar programas</descripcion>
        <transfondo>Artesano Gremial</transfondo>
        <alinemiento>Neutral Bueno</alinemiento>

        <vida>10</vida>
        <movimiento>25</movimiento>

        <nivel>1</nivel>
        <clase>Artificiero</clase>
        <experiencia>0</experiencia>

        <atributos>
            <fuerza>10</fuerza>
            <destreza>14</destreza>
            <constitucion>12</constitucion>
            <inteligencia>15</inteligencia>
            <sabiduria>15</sabiduria>
            <carisma>10</carisma>
        </atributos>

        <competencias>
            <bonificador>2</bonificador>
            <salvaciones>
                <atributo>Constitucion</atributo>
                <atributo>Inteligencia</atributo>
            </salvaciones>
            <idiomas>
                <idioma>Comun</idioma>
                <idioma>Enano</idioma>
                <idioma>Elfico</idioma>
            </idiomas>
        </competencias>

        <inventario>
            <objeto nombre="Cañon Trueno">
                <descripcion>
                    Cañon a distancia
                    Daño:2d6 perforante
                    Rango: 150-500 pies
                </descripcion>
            </objeto>
            <objeto nombre="Marillo ligero">
                <descripcion>
                    Pequeño martillo de guerra
                    Daño:8d
                </descripcion>
            </objeto>
            <objeto nombre="Armadura de cuero tachonada">
                <descripcion>
                    Armadura: 12
                </descripcion>
            </objeto>
        </inventario>

        <magias>
            <atributo>Inteligencia</atributo>
            <salvacion>12</salvacion>
            <bonificador>4</bonificador>
            <nivelMagia n="0">
                <usos>20</usos>
                <magia nombre="Remendar">
                    <descripcion>Este conjuro repara una única rotura o rasgadura en un objeto que
                        toques, como un eslabón roto de una cadena, dos mitades de una
                        llave rota, una capa desgarrada, o un odre con filtraciones. Siempre
                        y cuando la rotura o rasgadura no sea mayor de 1 pie (30 cm) en
                        cualquier dimensión, la arreglas, y no queda rastro alguno del daño
                        anterior.
                        Este conjuro puede reparar físicamente un objeto mágico o a un
                        constructo, pero el conjuro no puede restaurar la magia a objetos
                        de dicho tipo.</descripcion>
                    <componentes>Voz</componentes>
                </magia>
                <magia nombre="Identificar">
                    <descripcion>Eliges un objeto que debes estar tocando mientras realizas este
                        conjuro. Si es un objeto mágico o algún tipo de objeto con magia
                        imbuida, aprendes sus propiedades y cómo usarlas, ya sea que
                        requiera vinculación, y cuantas cargas posee, si es que tiene alguna.
                        Aprendes si algún conjuro está afectando el objeto y que es lo que
                        hace. Si el objeto fue creado por un conjuro, aprendes que conjuro
                        lo creo.
                        Si en su lugar tocas a una criatura mientras realizas el
                        conjuro, aprendes que conjuros, si es que hay alguno, está
                        actualmente afectándolo.</descripcion>
                    <componentes>Voz, tacto</componentes>
                </magia>
            </nivelMagia>
        </magias>
    </personaje>

    <personaje nombre="Prueba">
        <raza>Probadores</raza>
        <descripcion>Personaje de prueba para el tutorial</descripcion>
        <transfondo>Prueba</transfondo>
        <alinemiento>Neutral Neutral</alinemiento>
        <vida>10</vida>
        <movimiento>10</movimiento>
        <nivel>1</nivel>
        <clase>Probador</clase>
        <experiencia>1</experiencia>
        <atributos>
            <fuerza>1</fuerza>
            <destreza>20</destreza>
            <constitucion>20</constitucion>
            <inteligencia>1</inteligencia>
            <sabiduria>20</sabiduria>
            <carisma>15</carisma>
        </atributos>
        <competencias>
            <bonificador>4</bonificador>
            <salvaciones>
                <atributo>Fuerza</atributo>
                <atributo>Inteligencia</atributo>
            </salvaciones>
            <idiomas>
                <idioma>Binario</idioma>
            </idiomas>
        </competencias>
        <inventario>
            <objeto nombre="Tester">
                <descripcion>Objeto de prueba</descripcion>
            </objeto>
        </inventario>
        <magias>
            <atributo>Inteligencia</atributo>
            <salvacion>4</salvacion>
            <bonificador>4</bonificador>
            <nivelMagia n="1">
                <usos>1</usos>
                <magia nombre="Prueba">
                    <descripcion>Magia probatoria</descripcion>
                    <componentes>Debuger</componentes>
                </magia>
            </nivelMagia>
        </magias>
    </personaje>

    <personaje nombre="Kursk">
        <raza>Semiorco</raza>
        <descripcion>El vijo y veterano kursk lucho en las guerras de peñasa y ha vuelto para patear a todabia mas gente</descripcion>
        <transfondo>Héroe del pueblo</transfondo>
        <alinemiento>Caotico Neutral</alinemiento>
        <vida>120</vida>
        <movimiento>40</movimiento>
        <nivel>20</nivel>
        <clase>Barbaro</clase>
        <experiencia>680</experiencia>
        <atributos>
            <fuerza>20</fuerza>
            <destreza>15</destreza>
            <constitucion>19</constitucion>
            <inteligencia>15</inteligencia>
            <sabiduria>12</sabiduria>
            <carisma>16</carisma>
        </atributos>
        <competencias>
            <bonificador>4</bonificador>
            <salvaciones>
                <atributo>Fuerza</atributo>
                <atributo>Constitucion</atributo>
            </salvaciones>
            <idiomas>
                <idioma>Semiorco</idioma>
                <idioma>Comun</idioma>
            </idiomas>
        </competencias>
        <inventario>
            <objeto nombre="La puerta">
                <descripcion>La legendaria puerta de las antiguas leyendas. Daño: 2d12 Contundente</descripcion>
            </objeto>
            <objeto nombre="Armadura Cuero tachonado">
                <descripcion>CA 12 + Des</descripcion>
            </objeto>
        </inventario>
        <magias>
            <atributo>Inteligencia</atributo>
            <salvacion>2</salvacion>
            <bonificador>2</bonificador>
        </magias>
    </personaje>

    <personaje nombre="pipo">
        <raza>popo</raza>
        <descripcion>des</descripcion>
        <transfondo>mopo</transfondo>
        <alinemiento>mip</alinemiento>
        <vida>50</vida>
        <movimiento>1</movimiento>
        <nivel>2</nivel>
        <clase>Don</clase>
        <experiencia>0</experiencia>
        <atributos>
            <fuerza>1</fuerza>
            <destreza>1</destreza>
            <constitucion>1</constitucion>
            <inteligencia>1</inteligencia>
            <sabiduria>1</sabiduria>
            <carisma>1</carisma>
        </atributos>
        <competencias>
